name: iq_center
version: 1.0.0+1
description: "IQ CENTER - Professional Game Center System for PC Control via MAC Address"
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.1
  network_info_plus: ^6.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
