// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: xafxjabosshiesrtidgg

class SupabaseConfig {
  static const String supabaseUrl = 'https://xafxjabosshiesrtidgg.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZnhqYWJvc3NoaWVzcnRpZGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NTQ1MTIsImV4cCI6MjA3NzEzMDUxMn0.8CnuI9ghBfDuyfiGul0W6J3ikpoSQtmKOdLM0yUTQe8';
}
